# Generated by Django 5.2.9 on 2026-04-26 10:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=255)),
                (
                    "registration_number",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid registration number format. Example: u21co1001, u21mls1001, u21msde1001.",
                                regex="^u\\d{2}[a-zA-Z]{2,4}\\d{4}$",
                            )
                        ],
                    ),
                ),
                ("profile_image", models.URLField(blank=True, null=True)),
                (
                    "fingerprint_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "db_table": "students",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
