# Generated by Django 5.2.9 on 2026-04-26 10:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "semester",
                    models.PositiveSmallIntegerField(choices=[(1, "1"), (2, "2")]),
                ),
                ("session", models.CharField(max_length=32)),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True, related_name="registrations", to="courses.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_registrations",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "course_registrations",
                "ordering": ["-created_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "semester", "session"),
                        name="unique_registration_per_student_semester_session",
                    )
                ],
            },
        ),
    ]
