# Generated by Django 5.2.9 on 2026-04-26 10:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("leader_name", models.CharField(max_length=255)),
                ("leader_phone", models.CharField(max_length=50)),
                ("leader_email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "faculties",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
