# Generated by Django 5.2.9 on 2026-04-26 10:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course_title", models.CharField(max_length=255)),
                ("course_code", models.CharField(max_length=50)),
                (
                    "credit_unit",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "semester",
                    models.PositiveSmallIntegerField(choices=[(1, "1"), (2, "2")]),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "db_table": "courses",
                "ordering": ["-created_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("department", "course_code"),
                        name="unique_course_code_per_dept",
                    )
                ],
            },
        ),
    ]
