# Generated by Django 5.2.9 on 2026-04-26 10:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=4)),
                ("is_used", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("purpose", models.CharField(default="login", max_length=50)),
            ],
            options={
                "db_table": "otps",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OTPThrottle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
                ("purpose", models.CharField(default="login", max_length=50)),
                ("kind", models.CharField(max_length=20)),
                ("bucket", models.DateTimeField()),
            ],
            options={
                "db_table": "otp_throttle",
            },
        ),
    ]
