# Generated by Django 5.2.9 on 2026-04-26 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="otpthrottle",
            index=models.Index(
                fields=["email", "purpose", "kind", "bucket"],
                name="otp_throttl_email_9d3538_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="otpthrottle",
            index=models.Index(fields=["bucket"], name="otp_throttl_bucket_ddec5d_idx"),
        ),
        migrations.AddConstraint(
            model_name="otpthrottle",
            constraint=models.UniqueConstraint(
                fields=("email", "purpose", "kind", "bucket"),
                name="uniq_otp_throttle_email_purpose_kind_bucket",
            ),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(
                fields=["user", "code", "is_used"], name="otps_user_id_16d9f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(fields=["expires_at"], name="otps_expires_f6308f_idx"),
        ),
    ]
