# Generated by Django 5.2.9 on 2026-04-26 10:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("faculty", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("leader_name", models.CharField(max_length=255)),
                ("leader_phone", models.CharField(max_length=50)),
                ("leader_email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=255)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="faculty.faculty",
                    ),
                ),
            ],
            options={
                "db_table": "departments",
                "ordering": ["-created_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("faculty", "name"), name="unique_department_per_faculty"
                    )
                ],
            },
        ),
    ]
